[build]
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.147.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

#[[plugins]]
#package = "netlify-plugin-image-optim"

# [[plugins]]
# package = "netlify-plugin-is-website-vulnerable"


[[plugins]]
package = "netlify-plugin-js-obfuscator"

# All inputs are optional, so you can omit this section.
# Defaults are shown below.
# You can also refer to `javascript-obfuscator`’s documentation: https://github.com/javascript-obfuscator/javascript-obfuscator.
[plugins.inputs]
# Compact code output on one line.
compact = true
# Enables numbers conversion to expressions
numbersToExpressions = true
# Enables additional code obfuscation through simplification.
simplify = true
# Randomly shuffles the stringArray array items
shuffleStringArray = true
# Splits literal strings into chunks with length of splitStringsChunkLength option value
splitStrings = true


[[plugins]]
package = "netlify-plugin-hugo-cache-resources"
[plugins.inputs]
# If it should show more verbose logs (optional, default = true)
debug = true
